using System;
using System.IO;
using System.Text;
using System.Diagnostics;

namespace CoffLoader
{
    public class Program
    {
        // Class-level variables to hold output data
        private static string beaconOutputData;
        private static int beaconOutputData_sz = 0;

        public static void Main(string[] args)
        {
            if (args.Length != 3)
            {
                Console.WriteLine("USAGE: coffloader.exe <functionName> <bof filename> <arguments>");
                Console.WriteLine("\tExample: coffloader.exe go whoami.o 00");
                return;
            }

            try
            {
                string functionName = args[0];
                byte[] rawCoff = File.ReadAllBytes(args[1]);
                string coffData = Convert.ToBase64String(rawCoff);
                string argDataHex = Convert.ToBase64String(Encoding.Default.GetBytes(args[2]));

                string result = RunCoff(functionName, coffData, argDataHex);

                Console.WriteLine(result);
                string output = BeaconGetOutputData();
                Console.WriteLine(output);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error occurred: {ex.Message}");
            }
        }

        public static string RunCoff(string functionName, string coffData, string argDataHex)
        {
            string Result = "";

            try
            {
                Debug.WriteLine("Calling RunCoff()");

                byte[] functionname = Encoding.ASCII.GetBytes(functionName);
                byte[] coff_data = Decode(coffData);
                byte[] arg_data = HexToBytes(Encoding.ASCII.GetString(Decode(argDataHex)));
                byte[] beacon_data = Decode("ZIYKAAAAAADODgAAQgAAAAAABAAudGV4dAAAAAAAAAAAAAAAgAUAAKQBAADECQAAAAAAAC8AAAAgAFBgLmRhdGEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQABQwC5ic3MAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAIAAUMAvNAAAAAAAAAAAAAAAAAAAEAAAACQHAACaCwAAAAAAAAEAAAAgAFBgLzE4AAAAAAAAAAAAAAAAAAgAAAA0BwAAAAAAAAAAAAAAAAAAQAAwQC8zMwAAAAAAAAAAAAAAAAAMAAAAPAcAAKQLAAAAAAAAAwAAAEAAMEAueGRhdGEAAAAAAAAAAAAA1AAAAEgHAAAAAAAAAAAAAAAAAABAADBALnBkYXRhAAAAAAAAAAAAADgBAAAcCAAAwgsAAAAAAABOAAAAQAAwQC5yZGF0YQAAAAAAAAAAAABQAAAAVAkAAAAAAAAAAAAAAAAAAEAAUEAvNDgAAAAAAAAAAAAAAAAAIAAAAKQJAAAAAAAAAAAAAAAAAABAAFBAuAUVAAAPvhFI/8GE0nQHa8AhAdDr78OJyA/Iw0iFyXQcSIXSdBdBg+gESIkRSIPCBESJQRBEiUEUSIlRCMNTSIPsMEiJy0iFyXUEMcDrLjHAg3kQA4lEJCx+8EiLUQhBuAQAAABIjUwkLP8VAAAAAEiDQwgEi0QkLINrEARIg8QwW8NTSIPsMEiJy0iFyXUEMcDrMIN5EAFmx0QkLgAAfu9Ii1EIQbgCAAAASI1MJC7/FQAAAABIg0MIAmaLRCQug2sQAkiDxDBbwzHASIXJdAOLQRDDVlNIg+w4SInLSInWSIXJdQQxwOtIMcCDeRADiUQkLH7wSItRCEG4BAAAAEiNTCQs/xUAAAAAi0sQi1QkLEiLQwiD6QQp0UiDwASJSxCJ0UgBwUiJSwhIhfZ0AokWSIPEOFtew1ZTSIPsKEiJy4nWSIXJdB1IY8q6AQAAAP8VAAAAAIlzFEiJA0iJQwgxwIlDEEiDxChbXsNTSIPsIEiJy0iFyXQcTGNBFDHSSIsJ/xUAAAAASIsDSIlDCItDFIlDEEiDxCBbw1NIg+wgSInLSIXJdB1IiwlIhcl0C/8VAAAAADHSSIkTMcBIiUMISIlDEEiDxCBbw1dWU0iD7CBIictEicZIhcl0HEiF0nQXSWP4SItJCEmJ+P8VAAAAAEgBewgBcxBIg8QgW15fw1VXVlNIg+xITImEJIAAAABIictIiddMiYwkiAAAAEiFyXRUSIXSdE9MjYwkgAAAAEmJ0EiLLQAAAAAx0kyJTCQ4MclMiUwkKP/VSGPwi0MQAfA7QxR9IEyLTCQojVYBSItLCEmJ+Ehj0kyJTCQ4/9UBcxBIAXMISIPESFteX13DSIXJdA9IhdJ0CotBEIkCSIsB6wIxwMNTSIPsMEiJy4nRSIXbdDKLQxCDwAM7QxR9J+hf/f//SI1UJCxIi0sIQbgEAAAAiUQkLP8VAAAAAINDEARIg0MIBEiDxDBbw1VXVlNIg+w4TIlEJHBIidZMiUwkeEiF0g+EigAAAEiNbCRwMclJidAx0kiJbCQoSIs9AAAAAEmJ6f/XixUEAAAASIsNCAAAAInDAcL/wkhj0v8VAAAAAEiFwHRMSGMVAAAAAP/DSIkFCAAAAEhj20iNDBBJidgx0v8VAAAAAEiJbCQoSYnpSYnwSGMNAAAAAEiJ2kgDDQgAAAD/1wEFBAAAAAEFAAAAAEiDxDhbXl9dw1ZTSIPsKEiJ1kSJw0iF0nRnixUEAAAASIsNCAAAAEQBwv/CSGPS/xUAAAAASIkFCAAAAEiFwHRASGMVAAAAAESNQwFNY8BIjQwQMdL/FQAAAABIYw0AAAAATGPDSInySAMNCAAAAP8VAAAAAAEdBAAAAAEdAAAAAEiDxChbXsNIg+woSInKMcn/FQAAAAC4AQAAAEiDxCjDSP8lAAAAADHAw1VXVlNIg+woSInXSWPwSIXSdEKFyUiNHSEAAABIjQUAAAAASIstAAAAAEgPRdhIidn/1Ug5xnIdSInZ/9VIidpIiflJicBIg8QoW15fXUj/JQAAAABIg8QoW15fXcNIg+xYMcBIjRUAAAAATIlMJEhFMclMiUQkQEUxwIXJSIlEJDhIiUQkMEiLBQAAAADHRCQoAAAACMdEJCABAAAAdQdIjRUhAAAAMcn/0EiDxFjDw8NWU0iD7ChIictIhcl0HEiLNQAAAABIi0kI/9ZIiwtIifBIg8QoW15I/+BIg8QoW17DSIPsODHAQYP4AX4kTWPASIlUJCBBg8n/uggAAABJ0ehEiUQkKEmJyDHJ/xUAAAAASIPEOMNIichIhcl0KYsNBAAAAEiLFQgAAACJCDHJMcCJDQQAAACJDQAAAABIiQUIAAAASInQw5CQkEiD7CjoAAAAADHASIPEKMMBBAEABEIAAAAAAAAQAAAAAAAAAAEAAAABAAAAAQAAAAEFAgAFUgEwAQUCAAVSATABAAAAAQYDAAZiAjABYAAAAQYDAAZCAjABYAAAAQUCAAUyATABBQIABTIBMAEHBAAHMgMwAmABcAEIBQAIggQwA2ACcAFQAAABAAAAAQUCAAVSATABCAUACGIEMANgAnABUAAAAQYDAAZCAjABYAAAAQQBAARCAAABAAAAAQAAAAEIBQAIQgQwA2ACcAFQAAABBAEABKIAAAEAAAABAAAAAQYDAAZCAjABYAAAAQQBAARiAAABAAAAAAAAABcAAAAAAAAAFwAAABwAAAAEAAAAHAAAAD4AAAAIAAAAPgAAAIMAAAAMAAAAgwAAAMoAAAAUAAAAygAAANUAAAAcAAAA1QAAADkBAAAgAAAAOQEAAG0BAAAsAAAAbQEAAJwBAAA4AAAAnAEAAMwBAABAAAAAzAEAAAICAABIAAAAAgIAAIICAABUAAAAggIAAJkCAABkAAAAmQIAAOACAABoAAAA4AIAAJEDAABwAAAAkQMAABAEAACAAAAAEAQAACkEAACMAAAAKQQAADAEAACUAAAAMAQAADMEAACYAAAAMwQAAJEEAACcAAAAkQQAAOMEAACsAAAA4wQAAOQEAAC0AAAA5AQAAOUEAAC4AAAA5QQAABYFAAC8AAAAFgUAAEsFAADIAAAASwUAAH0FAADQAAAAQzpcV2luZG93c1xTeXNXT1c2NFxydW5kbGwzMi5leGUAQzpcV2luZG93c1xTeXN0ZW0zMlxydW5kbGwzMi5leGUAAAAAAAAAAAAAAAAAAABHQ0M6IChHTlUpIDEzLXdpbjMyAAAAAAAAAAAAAAAAAGwAAAA2AAAABACyAAAANgAAAAQABwEAADYAAAAEAFMBAAA3AAAABACFAQAAOAAAAAQAswEAADkAAAAEAO8BAAA2AAAABAA4AgAAOgAAAAQAzQIAADYAAAAEABIDAAA6AAAABAAdAwAAIgAAAAQAJAMAACIAAAAEADMDAAA7AAAABAA/AwAAIgAAAAQASAMAACIAAAAEAFoDAAA4AAAABABsAwAAIgAAAAQAdgMAACIAAAAEAH4DAAAiAAAABACEAwAAIgAAAAQApAMAACIAAAAEAKsDAAAiAAAABAC5AwAAOwAAAAQAwAMAACIAAAAEAMwDAAAiAAAABADfAwAAOAAAAAQA5gMAACIAAAAEAPMDAAAiAAAABAD5AwAANgAAAAQA/wMAACIAAAAEAAUEAAAiAAAABAAbBAAAPAAAAAQALAQAAD0AAAAEAEsEAAAuAAAABABSBAAALgAAAAQAWQQAAD4AAAAEAIQEAAA2AAAABACaBAAALgAAAAQAvQQAAD8AAAAEANYEAAAuAAAABAD2BAAAQAAAAAQAQgUAAEEAAAAEAFUFAAAiAAAABABcBQAAIgAAAAQAaAUAACIAAAAEAG4FAAAiAAAABAB1BQAAIgAAAAQABQAAADUAAAAEAAAAAAAkAAAAAwAEAAAAJAAAAAMACAAAACYAAAADAAAAAAAeAAAAAwAEAAAAHgAAAAMACAAAACoAAAADAAwAAAAeAAAAAwAQAAAAHgAAAAMAFAAAACoAAAADABgAAAAeAAAAAwAcAAAAHgAAAAMAIAAAACoAAAADACQAAAAeAAAAAwAoAAAAHgAAAAMALAAAACoAAAADADAAAAAeAAAAAwA0AAAAHgAAAAMAOAAAACoAAAADADwAAAAeAAAAAwBAAAAAHgAAAAMARAAAACoAAAADAEgAAAAeAAAAAwBMAAAAHgAAAAMAUAAAACoAAAADAFQAAAAeAAAAAwBYAAAAHgAAAAMAXAAAACoAAAADAGAAAAAeAAAAAwBkAAAAHgAAAAMAaAAAACoAAAADAGwAAAAeAAAAAwBwAAAAHgAAAAMAdAAAACoAAAADAHgAAAAeAAAAAwB8AAAAHgAAAAMAgAAAACoAAAADAIQAAAAeAAAAAwCIAAAAHgAAAAMAjAAAACoAAAADAJAAAAAeAAAAAwCUAAAAHgAAAAMAmAAAACoAAAADAJwAAAAeAAAAAwCgAAAAHgAAAAMApAAAACoAAAADAKgAAAAeAAAAAwCsAAAAHgAAAAMAsAAAACoAAAADALQAAAAeAAAAAwC4AAAAHgAAAAMAvAAAACoAAAADAMAAAAAeAAAAAwDEAAAAHgAAAAMAyAAAACoAAAADAMwAAAAeAAAAAwDQAAAAHgAAAAMA1AAAACoAAAADANgAAAAeAAAAAwDcAAAAHgAAAAMA4AAAACoAAAADAOQAAAAeAAAAAwDoAAAAHgAAAAMA7AAAACoAAAADAPAAAAAeAAAAAwD0AAAAHgAAAAMA+AAAACoAAAADAPwAAAAeAAAAAwAAAQAAHgAAAAMABAEAACoAAAADAAgBAAAeAAAAAwAMAQAAHgAAAAMAEAEAACoAAAADABQBAAAeAAAAAwAYAQAAHgAAAAMAHAEAACoAAAADACABAAAeAAAAAwAkAQAAHgAAAAMAKAEAACoAAAADACwBAAAeAAAAAwAwAQAAHgAAAAMANAEAACoAAAADAC5maWxlAAAAAAAAAP7/AABnAQAAAAA7AAAAAAAAAAAAAAAAAG1haW4AAAAAAAAAAAQAIAACAQAAAAAAAAAAAAAAAAAAAAAAAGhhc2hfZGpiAAAAAAEAIAACAAAAAABSAAAAFwAAAAEAIAACAAAAAABhAAAAHAAAAAEAIAACAAAAAABxAAAAPgAAAAEAIAACAAAAAAB/AAAAgwAAAAEAIAACAAAAAACPAAAAygAAAAEAIAACAAAAAACgAAAA1QAAAAEAIAACAAAAAACyAAAAOQEAAAEAIAACAAAAAADEAAAAbQEAAAEAIAACAAAAAADWAAAAnAEAAAEAIAACAAAAAADnAAAAzAEAAAEAIAACAAAAAAD6AAAAAgIAAAEAIAACAAAAAAANAQAAggIAAAEAIAACAAAAAAAiAQAAmQIAAAEAIAACAAAAAAAyAQAA4AIAAAEAIAACAAAAAAA/AQAAkQMAAAEAIAACAAAAAABMAQAAEAQAAAEAIAACAAAAAABbAQAAKQQAAAEAIAACAAAAAABtAQAAMAQAAAEAIAACAAAAAAB7AQAAMwQAAAEAIAACAAAAAACMAQAAkQQAAAEAIAACAAAAAACoAQAA4wQAAAEAIAACAAAAAAC8AQAA5AQAAAEAIAACAAAAAADZAQAA5QQAAAEAIAACAAAAAADuAQAAFgUAAAEAIAACAAAAAAD5AQAASwUAAAEAIAACAC50ZXh0AAAAAAAAAAEAAAADAX0FAAAvAAAAAAAAAAAAAAAAAC5kYXRhAAAAAAAAAAIAAAADAQAAAAAAAAAAAAAAAAAAAAAAAC5ic3MAAAAAAAAAAAMAAAADARAAAAAAAAAAAAAAAAAAAAAAAAAAAAANAgAAAAAAAAQAAAADARAAAAABAAAAAAAAAAAAAAAAAAAAAAAbAgAAAAAAAAUAAAADAQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAqAgAAAAAAAAYAAAADAQwAAAADAAAAAAAAAAAAAAAAAC54ZGF0YQAAAAAAAAcAAAADAdQAAAAAAAAAAAAAAAAAAAAAAC5wZGF0YQAAAAAAAAgAAAADATgBAABOAAAAAAAAAAAAAAAAAC5yZGF0YQAAAAAAAAkAAAADAUIAAAAAAAAAAAAAAAAAAAAAAAAAAAA5AgAAAAAAAAoAAAADARQAAAAAAAAAAAAAAAAAAAAAAAAAAABEAgAABAAAAAMAAAACAAAAAABeAgAACAAAAAMAAAACAAAAAAB6AgAAAAAAAAMAAAACAF9fbWFpbgAAAAAAAAAAIAACAAAAAACWAgAAAAAAAAAAAAACAAAAAACqAgAAAAAAAAAAAAACAAAAAAC+AgAAAAAAAAAAAAACAAAAAADSAgAAAAAAAAAAAAACAAAAAADkAgAAAAAAAAAAAAACAAAAAAD7AgAAAAAAAAAAAAACAAAAAAAQAwAAAAAAAAAAAAACAAAAAAAuAwAAAAAAAAAAAAACAAAAAABKAwAAAAAAAAAAAAACAAAAAABeAwAAAAAAAAAAAAACAAAAAAB8AwAAAAAAAAAAAAACAAAAAACXAwAAAAAAAAAAAAACALoDAAAudGV4dC5zdGFydHVwAC54ZGF0YS5zdGFydHVwAC5wZGF0YS5zdGFydHVwAC5yZGF0YSR6enoAYmVhY29uX2NvbXBhdGliaWxpdHkuYwBzd2FwX2VuZGlhbmVzcwBCZWFjb25EYXRhUGFyc2UAQmVhY29uRGF0YUludABCZWFjb25EYXRhU2hvcnQAQmVhY29uRGF0YUxlbmd0aABCZWFjb25EYXRhRXh0cmFjdABCZWFjb25Gb3JtYXRBbGxvYwBCZWFjb25Gb3JtYXRSZXNldABCZWFjb25Gb3JtYXRGcmVlAEJlYWNvbkZvcm1hdEFwcGVuZABCZWFjb25Gb3JtYXRQcmludGYAQmVhY29uRm9ybWF0VG9TdHJpbmcAQmVhY29uRm9ybWF0SW50AEJlYWNvblByaW50ZgBCZWFjb25PdXRwdXQAQmVhY29uVXNlVG9rZW4AQmVhY29uUmV2ZXJ0VG9rZW4AQmVhY29uSXNBZG1pbgBCZWFjb25HZXRTcGF3blRvAEJlYWNvblNwYXduVGVtcG9yYXJ5UHJvY2VzcwBCZWFjb25JbmplY3RQcm9jZXNzAEJlYWNvbkluamVjdFRlbXBvcmFyeVByb2Nlc3MAQmVhY29uQ2xlYW51cFByb2Nlc3MAdG9XaWRlQ2hhcgBCZWFjb25HZXRPdXRwdXREYXRhAC50ZXh0LnN0YXJ0dXAALnhkYXRhLnN0YXJ0dXAALnBkYXRhLnN0YXJ0dXAALnJkYXRhJHp6egBiZWFjb25fY29tcGF0aWJpbGl0eV9zaXplAGJlYWNvbl9jb21wYXRpYmlsaXR5X291dHB1dABiZWFjb25fY29tcGF0aWJpbGl0eV9vZmZzZXQAX19pbXBfTVNWQ1JUJG1lbWNweQBfX2ltcF9NU1ZDUlQkY2FsbG9jAF9faW1wX01TVkNSVCRtZW1zZXQAX19pbXBfTVNWQ1JUJGZyZWUAX19pbXBfTVNWQ1JUJHZzbnByaW50ZgBfX2ltcF9NU1ZDUlQkcmVhbGxvYwBfX2ltcF9BRFZBUEkzMiRTZXRUaHJlYWRUb2tlbgBfX2ltcF9BRFZBUEkzMiRSZXZlcnRUb1NlbGYAX19pbXBfTVNWQ1JUJHN0cmxlbgBfX2ltcF9LRVJORUwzMiRDcmVhdGVQcm9jZXNzQQBfX2ltcF9LRVJORUwzMiRDbG9zZUhhbmRsZQBfX2ltcF9LRVJORUwzMiRNdWx0aUJ5dGVUb1dpZGVDaGFyAA==");

                // Initialize Beacon* functions
                if (CoffParser.parseCOFF(new byte[] { }, beacon_data, beacon_data.Length, null, 0) == 1)
                {
                    CoffParser.CleanUpMemoryAllocations();
                    return "parseCOFF Beacon compat failed: 1";
                }

                Debug.WriteLine("************************ BEACON PROCESSING DONE ***********************");

                // Parse the COFF file
                if (CoffParser.parseCOFF(functionname, coff_data, coff_data.Length, arg_data, arg_data.Length) == 1)
                {
                    Result = "ERROR";
                    beaconOutputData = "parseCOFF failed: 1";
                    beaconOutputData_sz = beaconOutputData.Length;
                    CoffParser.CleanUpMemoryAllocations();
                }
                else
                {
                    beaconOutputData = CoffParser.getBeaconOutputData();
                    beaconOutputData_sz = beaconOutputData.Length;
                    CoffParser.CleanUpMemoryAllocations();
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine($"Exception: '{e}'");
            }

            return Result;
        }

        public static int BeaconGetOutputData_Size()
        {
            return beaconOutputData_sz;
        }

        public static string BeaconGetOutputData()
        {
            return beaconOutputData;
        }

        public static string unhexlify(string hex)
        {
            string ret = null;
            for (int i = 0; i < hex.Length - 1; i += 2)
            {
                int value = Convert.ToInt32(hex.Substring(i, 2), 16);
                ret += char.ConvertFromUtf32(value);
            }
            return ret;
        }

        private static byte[] HexToBytes(string hex)
        {
            if (hex.Length % 2 != 0)
                hex = "0" + hex;
            byte[] result = new byte[hex.Length / 2];
            for (int i = 0; i < result.Length; i++)
                result[i] = Convert.ToByte(hex.Substring(i * 2, 2), 16);
            return result;
        }

        public static byte[] Decode(string encodedBuffer)
        {
            return Convert.FromBase64String(encodedBuffer);
        }
    }
}
